Use a callback based solution for geocode function
UI test runner doesn't like it saying,

SEVERE: Execute com.byagowi.persiancalendar.ui.dialogs.CoordinatesDialogTest.cancelButtonTest: FAILED
java.lang.IllegalStateException: java.lang.IllegalStateException: Required value was null.
at com.byagowi.persiancalendar.utils.CoordinatesUtilsKt$geocode$2.invokeSuspend(CoordinatesUtils.kt:55)
...
Suppressed: androidx.compose.runtime.tooling.DiagnosticComposeException: Composition stack when thrown: