qr: Replace some of the forEach uses with simpler for
Because of false alarm of,

persian-calendar/PersianCalendar/src/main/kotlin/com/byagowi/persiancalendar/ui/converter/Qr.kt:116: Error: Call requires API level 24 (current min is 17): java.lang.Iterable#forEach [NewApi]
        pos.forEach { col ->