Disable events tab parent animation
Causes crashes when different days clicked, let's avoid for now.

RecyclcerView's animation still exists.

Thanks to Ali Mahdavi for discovering the issue,

java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: EventViewHolder{67bbd42 position=0 id=-1, oldPos=-1, pLpos:-1 update tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{694debe VFED.V... ......ID 0,42-1440,997 #7f0800e7 app:id/events}, adapter:com.byagowi.persiancalendar.ui.calendar.EventsRecyclerViewAdapter@ca6b5c3, layout:androidx.recyclerview.widget.LinearLayoutManager@ac4d49, context:com.byagowi.persiancalendar.ui.MainActivity@863e1ac
  at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:7077)
  at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1597)
  at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:13655)
  at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:14157)
  at androidx.recyclerview.widget.SimpleItemAnimator.dispatchChangeFinished(SimpleItemAnimator.java:328)
  at androidx.recyclerview.widget.DefaultItemAnimator$8.onAnimationEnd(DefaultItemAnimator.java:397)
  at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
  at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:711)
  at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda1.call(Unknown Source:4)
  at android.animation.Animator.callOnList(Animator.java:669)
  at android.animation.Animator.notifyListeners(Animator.java:608)
  at android.animation.Animator.notifyEndListeners(Animator.java:633)
  at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1306)
  at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1566)
  at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
  at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
  at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
  at android.view.Choreographer.doCallbacks(Choreographer.java:952)
  at android.view.Choreographer.doFrame(Choreographer.java:878)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
  at android.os.Handler.handleCallback(Handler.java:958)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:205)
  at android.os.Looper.loop(Looper.java:294)
  at android.app.ActivityThread.main(ActivityThread.java:8177)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)