Let's cast faq to nullable
For some reason on rare cases faq can be null, let's write a defensive code for it, hopefully.

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.text.Regex.split, parameter input
	at kotlin.text.Regex.split(Unknown Source:2)
	at com.byagowi.persiancalendar.ui.about.AboutScreenKt.HelpItems(AboutScreen.kt:306)
	at com.byagowi.persiancalendar.ui.about.AboutScreenKt.access$HelpItems(AboutScreen.kt:1)