Use for loop instead of forEach
It gives seemingly false alarms like this,

persian-calendar/PersianCalendar/src/main/kotlin/com/byagowi/persiancalendar/ui/calendar/times/SunView.kt:113: Error: Call requires API level 24 (current min is 17): java.lang.Iterable#forEach [NewApi]
            (0..width).forEach { x ->
                       ~~~~~~~

Let's avoid and use plain old for each loop where it complains (which interestingly isn't everywhere)